### ISSUE TITLE
Engineer - Dependabot Configuration - Package Updates

### ISSUE THREAD

**Issue by rgarfield11** [rgarfield11/text_chunker_ex#3]
## Background
Our open source Elixir library 'Text Chunker' needs Dependabot set up to keep dependencies up-to-date automatically, ensuring our package management is proactive with updates and potential security vulnerabilities.

### Scenario: Automatic dependency updates with Dependabot
Given our repository for the 'Text Chunker' project is hosted on GitHub
- [ ] When Dependabot is enabled for the 'Text Chunker' repository
- [ ] Then it should check for updates to our dependencies on a daily basis
- [ ] And it should open pull requests automatically when updates are available
- [ ] And the pull requests should provide details of what has changed, including any potential security impact. 

 _created by ross.garfield+demo@revelry.co using [Prodops](https://app.prodops.ai)_

**Comment by rgarfield11** [comment]
It looks like the main goal here is to set up and configure Dependabot for the 'Text Chunker' Elixir library to automatically update its dependencies. Dependabot is a service integrated into GitHub that checks for outdated dependencies and opens pull requests to update them.

Since the configuration for Dependabot is not done in the codebase but rather in its GitHub repository settings, the following instructions will guide you through setting up Dependabot:

1. Create a `.github/dependabot.yml` file in the root directory of the 'Text Chunker' repository:

```yaml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "hex"    # Package manager for Elixir/OTP
    directory: "/"               # Location of package manifests
    schedule:
      interval: "daily"          # Check for updates daily
    open-pull-requests-limit: 10 # Limit for open pull requests
    ignore:
      - dependency-name: "ex_doc" # This version is to be updated manually
        versions: ["0.31"]       # Ignore this version
```

2. Make sure you commit and push this file to the GitHub repository.

3. Once the file is committed, Dependabot will start to check for updates daily. If it finds any, it will open pull requests with the changes, which will include the update details and any relevant compatibility scores or security vulnerability information.

4. Review and merge these pull requests as they come in to keep your dependencies up-to-date.

Here is some additional Elixir code that could be used to create the `dependabot.yml` file programmatically, although it is typically simpler to just create and modify this file manually:

```elixir
defmodule TextChunker.DependabotConfig do
  @config_path ".github/dependabot.yml"

  def create_config_file do
    File.write!(@config_path, dependabot_config())
  end

  defp dependabot_config do
    """
    version: 2
    updates:
      - package-ecosystem: "hex"    # Package manager for Elixir/OTP
        directory: "/"               # Location of package manifests
        schedule:
          interval: "daily"          # Check for updates daily
        open-pull-requests-limit: 10 # Limit for open pull requests
        ignore:
          - dependency-name: "ex_doc" # This version is to be updated manually
            versions: ["0.31"]       # Ignore this version
    """
  end
end

# Call this function to create the Dependabot configuration file
TextChunker.DependabotConfig.create_config_file()
```

Remember that to enable automatic merging of pull requests and add more granular configuration options, you might need to use the GitHub settings interface or the GitHub API. 

 _created by ross.garfield+demo@revelry.co using [Prodops](https://app.prodops.ai)_

**Comment by rgarfield11** [comment]
To solve the main problem the programmer is facing with setting up Dependabot for their Elixir library 'Text Chunker,' they will need to add a Dependabot configuration file to their GitHub repository. The file `.github/dependabot.yml` should enable Dependabot to check for updates to their dependencies, such as hex packages, on a daily basis and automatically open pull requests with details of what has changed.

Here is what the `.github/dependabot.yml` configuration file could look like:

```yaml
version: 2
updates:
  # Maintain dependencies for Elixir
  - package-ecosystem: "hex"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all" # Include "direct" "indirect" dependencies
    ignore:
      - dependency-name: "ecto" # Example of ignoring updates for a specific dependency
        versions: ["3.8.x"] # Example of ignoring specific versions
```

You should commit this file to the root of the 'Text Chunker' repository, specifically in the `.github` directory.

Dependabot will check for updates for Elixir dependencies specified in the `mix.exs` file. If updates are found, it will create pull requests according to the given configuration with the details about the updates, and if there are any security vulnerabilities, those will be highlighted too.

In order to test and verify Dependabot's operation, you'll need to merge this file into the default branch and wait for the next cycle the bot runs on (daily, as specified) or manually trigger it via GitHub's UI if immediate testing is needed.

Given the context and codebase provided, no other changes appear necessary for setting up Dependabot in this scenario. 

 _created by ross.garfield+demo@revelry.co using [Prodops](https://app.prodops.ai)_
